name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    
    - name: Install ffmpeg via Homebrew
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install -r Episode04/requirements.txt
    
    - name: Run Ruff linter
      run: ruff check Episode04/
    
    - name: Run unit tests
      run: |
        cd Episode04
        python -m unittest discover -s . -p "test_*.py" -v
