name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    
    - name: Cache Homebrew packages
      uses: actions/cache@v3
      with:
        path: |
          /home/linuxbrew/.linuxbrew/Cellar/ffmpeg
          /home/linuxbrew/.linuxbrew/lib
        key: homebrew-packages-${{ runner.os }}-ffmpeg-v1
        restore-keys: |
          homebrew-packages-${{ runner.os }}-
    
    - name: Install ffmpeg via Homebrew
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        if ! command -v ffmpeg &> /dev/null; then
          brew install ffmpeg
        fi
    
    - name: Install and start Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        ollama serve &
        sleep 10
    
    - name: Cache Ollama models
      uses: actions/cache@v3
      with:
        path: ~/.ollama
        key: ollama-models-bge-m3-v1
        restore-keys: |
          ollama-models-
    
    - name: Pull BGE-M3 model
      run: |
        if ! ollama list | grep -q "bge-m3"; then
          ollama pull bge-m3
        fi
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages
        key: python-packages-${{ runner.os }}-${{ hashFiles('Episode04/requirements.txt') }}-v1
        restore-keys: |
          python-packages-${{ runner.os }}-
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies with GitHub Actions Python..."
        which python3
        python3 --version
        python3 -m pip install --upgrade pip
        
        # Check if key packages are already installed (from cache)
        if python3 -c "import whisper" 2>/dev/null; then
          echo "✅ Whisper already installed (from cache)"
        else
          echo "📦 Installing packages from requirements.txt..."
          python3 -m pip install -r Episode04/requirements.txt
        fi
        
        # Install ruff separately (lightweight)
        python3 -m pip install ruff
        
        echo "Verifying installations..."
        python3 -m pip list | grep -i whisper || echo "Whisper not found in pip list"
        python3 -c "import whisper; print('Whisper import successful')" || echo "Whisper import failed"
    
    - name: Run Ruff linter
      run: ruff check Episode04/
    
    - name: Run unit tests
      run: |
        cd Episode04
        python -m unittest discover -s . -p "test_*.py" -v
    
    - name: Run integration tests
      run: |
        # Add ffmpeg to PATH but preserve GitHub Actions Python
        GITHUB_PYTHON=$(which python3)
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
        export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
        export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
        echo "Checking environment..."
        echo "GitHub Actions Python: $GITHUB_PYTHON"
        echo "Current python3 (after PATH change): $(which python3)"
        $GITHUB_PYTHON --version
        $GITHUB_PYTHON -c "import whisper; print('whisper imported successfully')" || echo "whisper import failed"
        which ffmpeg || echo "ffmpeg not found"
        cd Episode04
        RAG_TEST_MAX_PDFS=5 $GITHUB_PYTHON integration_test_rag.py
