name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    
    - name: Install ffmpeg via Homebrew
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install ffmpeg
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies with GitHub Actions Python..."
        which python3
        python3 --version
        python3 -m pip install --upgrade pip
        python3 -m pip install ruff
        python3 -m pip install -r Episode04/requirements.txt
        echo "Verifying whisper installation..."
        python3 -m pip list | grep -i whisper || echo "Whisper not found in pip list"
        python3 -c "import whisper; print('Whisper import successful')" || echo "Whisper import failed"
    
    - name: Run Ruff linter
      run: ruff check Episode04/
    
    - name: Run unit tests
      run: |
        cd Episode04
        python -m unittest discover -s . -p "test_*.py" -v
    
    - name: Run integration tests
      run: |
        # Add ffmpeg to PATH but preserve GitHub Actions Python
        GITHUB_PYTHON=$(which python3)
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
        export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
        export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
        echo "Checking environment..."
        echo "GitHub Actions Python: $GITHUB_PYTHON"
        echo "Current python3 (after PATH change): $(which python3)"
        $GITHUB_PYTHON --version
        $GITHUB_PYTHON -c "import whisper; print('whisper imported successfully')" || echo "whisper import failed"
        which ffmpeg || echo "ffmpeg not found"
        cd Episode04
        RAG_TEST_MAX_PDFS=999999 $GITHUB_PYTHON integration_test_rag.py
