name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Episode04/**' ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    
    - name: Cache Homebrew packages
      uses: actions/cache@v3
      with:
        path: |
          /home/linuxbrew/.linuxbrew/Cellar/ffmpeg
          /home/linuxbrew/.linuxbrew/lib
          /home/linuxbrew/.linuxbrew/var/homebrew/locks
        key: homebrew-packages-${{ runner.os }}-ffmpeg-v2
        restore-keys: |
          homebrew-packages-${{ runner.os }}-
    
    - name: Install ffmpeg
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        
        # Install or link ffmpeg via Homebrew
        if ! command -v ffmpeg &> /dev/null; then
          if brew list ffmpeg &> /dev/null; then
            echo "ffmpeg is installed but not linked. Linking..."
            brew link ffmpeg
          else
            echo "Installing ffmpeg via Homebrew..."
            brew install ffmpeg
          fi
        fi
        
        # If still not found, try apt-get as fallback
        if ! command -v ffmpeg &> /dev/null; then
          echo "Homebrew approach failed, installing ffmpeg via apt-get..."
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        fi
        
        echo "Checking ffmpeg installation:"
        which ffmpeg || echo "ffmpeg not found in PATH after installation"
        ffmpeg -version || echo "ffmpeg version check failed"
    
    - name: Install and start Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        ollama serve &
        sleep 10
    
    - name: Cache Ollama models
      uses: actions/cache@v3
      with:
        path: ~/.ollama
        key: ollama-models-bge-m3-v1
        restore-keys: |
          ollama-models-
    
    - name: Pull BGE-M3 model
      run: |
        if ! ollama list | grep -q "bge-m3"; then
          ollama pull bge-m3
        fi
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/whisper*
          /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/torch*
          /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/langchain*
          /opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/chromadb*
        key: python-packages-${{ runner.os }}-${{ hashFiles('Episode04/requirements.txt') }}-v2
        restore-keys: |
          python-packages-${{ runner.os }}-
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies with GitHub Actions Python..."
        which python3
        python3 --version
        python3 -m pip install --upgrade pip
        
        # Check if key packages are already installed (from cache)
        if python3 -c "import whisper" 2>/dev/null; then
          echo "✅ Whisper already installed (from cache)"
        else
          echo "📦 Installing packages from requirements.txt..."
          python3 -m pip install -r Episode04/requirements.txt
        fi
        
        # Install ruff separately (lightweight)
        python3 -m pip install ruff
        
        echo "Verifying installations..."
        python3 -m pip list | grep -i whisper || echo "Whisper not found in pip list"
        python3 -c "import whisper; print('Whisper import successful')" || echo "Whisper import failed"
    
    - name: Run Ruff linter
      run: ruff check Episode04/
    
    - name: Run unit tests
      run: |
        cd Episode04
        python -m unittest discover -s . -p "test_*.py" -v
    
    - name: Run integration tests
      run: |
        # Add ffmpeg to PATH but preserve GitHub Actions Python
        GITHUB_PYTHON=$(which python3)
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "Checking environment..."
        echo "GitHub Actions Python: $GITHUB_PYTHON"
        echo "Current python3 (after PATH change): $(which python3)"
        echo "PATH: $PATH"
        echo "HOMEBREW_PREFIX: $HOMEBREW_PREFIX"
        echo "Contents of Homebrew bin directory:"
        ls -la /home/linuxbrew/.linuxbrew/bin/ | head -10 || echo "Cannot list Homebrew bin directory"
        echo "Searching for ffmpeg in filesystem:"
        find /home/linuxbrew -name "ffmpeg*" 2>/dev/null | head -5 || echo "No ffmpeg found in Homebrew"
        $GITHUB_PYTHON --version
        $GITHUB_PYTHON -c "import whisper; print('whisper imported successfully')" || echo "whisper import failed"
        which ffmpeg || echo "ffmpeg not found in PATH"
        /home/linuxbrew/.linuxbrew/bin/ffmpeg -version || echo "Direct ffmpeg call failed"
        cd Episode04
        # Export environment variables for subprocess inheritance
        export PATH="$PATH"
        export HOMEBREW_PREFIX="$HOMEBREW_PREFIX"
        export HOMEBREW_CELLAR="$HOMEBREW_CELLAR" 
        export HOMEBREW_REPOSITORY="$HOMEBREW_REPOSITORY"
        RAG_TEST_MAX_PDFS=5 $GITHUB_PYTHON integration_test_rag.py
